# Generated by Django 5.2.7 on 2025-10-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotoblog', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='page_img',
            new_name='img',
        ),
    ]
