# Generated by Django 5.2.7 on 2025-10-23 19:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('content', models.TextField(blank=True, null=True)),
                ('page_img', models.ImageField(upload_to='page_img/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
