# Generated by Django 5.0.2 on 2025-11-04 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityControl', '0003_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='ziyaretci',
            name='tc_kimlik_no',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik Numarası 11 haneli olmalı ve 0 ile başlamamalıdır.', regex='^[1-9][0-9]{10}$')]),
        ),
    ]
