# Generated by Django 5.0.2 on 2025-11-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityControl', '0004_alter_page_slug_alter_ziyaretci_tc_kimlik_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='img',
            field=models.ImageField(default=1, upload_to='page_img/'),
            preserve_default=False,
        ),
    ]
