# Generated by Django 5.0.2 on 2025-11-04 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityControl', '0005_page_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taseron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=100)),
                ('davet_eden', models.CharField(max_length=100)),
                ('yapilacak_is', models.CharField(max_length=100)),
                ('calisma_alani', models.CharField(max_length=100)),
                ('is_inside', models.BooleanField(default=True)),
                ('is_outside', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ziyaretci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securityControl.ziyaretci')),
            ],
        ),
    ]
