# Generated by Django 5.0.2 on 2025-11-07 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityControl', '0006_taseron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taseron',
            name='is_outside',
        ),
        migrations.CreateModel(
            name='yuk_arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cekici_plaka', models.CharField(max_length=100, unique=True)),
                ('dorse_plaka', models.CharField(max_length=100, unique=True)),
                ('firma_adi', models.CharField(max_length=100)),
                ('arac_turu', models.CharField(max_length=100)),
                ('sevkiyat_bolumu', models.CharField(max_length=100)),
                ('gidecegi_yer', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('is_inside', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sofor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securityControl.ziyaretci')),
            ],
        ),
    ]
